# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy develop

on:
  push:
    branches: [ "develop" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SOLAR_SYSTEM_DEVELOP_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: create env file
        run: |
          touch .env
          echo GITHUB_TOKEN=${{ secrets.SOLAR_SYSTEM_DEVELOP_TOKEN }} >> .env

      - name: Build and deploy
        run: |
          npm install
          npm run deploy --no-silent
