name: Build and deploy develop
on:
  push:
    branches: [ "develop" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Build
        run: |
          npm install
          npm run buildCI

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.7.3
        with:
          branch: main
          folder: dist/solar-system/browser
          repository-name: lebesnec/solar-system-develop
          token: ${{ secrets.SOLAR_SYSTEM_DEVELOP_TOKEN }}

